#ifndef LAYA_TOKENIZER_H
#define LAYA_TOKENIZER_H

/*
 * Native Laya tokenizer.
 *
 * Implementation pattern adapted from o1.c src/model/tokenizer.c: static
 * tables generated by tools/laya_gen_c_tables.py + byte-level BPE. Only the
 * algorithm-specific pieces differ (mmBERT vocab, transformers ByteLevel
 * pre-tokenizer regex, NFC normalizer, added tokens with lstrip/rstrip).
 */

#include <stddef.h>

#include "laya.h"

/* Special token ids from the Laya tokenizer. */
#define LAYA_TOK_UNK  50280
#define LAYA_TOK_CLS  50281
#define LAYA_TOK_SEP  50282
#define LAYA_TOK_PAD  50283
#define LAYA_TOK_MASK 50284
#define LAYA_TOK_EOT  50279

/*
 * Encodes `text` with add_special_tokens=False semantics.
 * On success *out_ids is malloc'd (free with laya_tokenizer_free) and
 * *out_count holds the length.
 */
laya_status laya_tokenizer_encode(const char *text, int **out_ids, size_t *out_count);

/* Token id for an added-token content string, or -1. */
int laya_tokenizer_added_id(const char *content);

/* Decodes ids back to text (debug/verification only). Caller frees. */
laya_status laya_tokenizer_decode(const int *ids, size_t count, char **out);

void laya_tokenizer_free(int *ids);

/* Reads a JSON object {"text": [ids...]} and prints a pass/fail line per
   entry. Development-time parity check against the Python oracle. */
int tokenize_fixture(const char *path);

#endif /* LAYA_TOKENIZER_H */
